Mac 238 add training provider
SkillsFundingAgency/das-employer-accounts pull request #59
Opened 2023-10-02 10:19 UTC by cofaulco

2023-10-03 14:24 UTC, johrs requested changes

2023-10-03 14:24 UTC, johrs commented on src/SFA.DAS.EmployerAccounts.Web.UnitTests/Orchestrators/HomeOrchestratorTests/WhenGettingEmployerAccountAgreements.cs
Can this class be removed now?

2023-10-03 14:24 UTC, johrs commented on src/SFA.DAS.EmployerAccounts.Web/Orchestrators/HomeOrchestrator.cs
Commented code still in place

2023-10-03 14:24 UTC, johrs commented on src/SFA.DAS.EmployerAccounts/Services/ContentApiClient.cs
> +            var azureServiceTokenProvider = new ChainedTokenCredential(
Would be nicer to inject a service class which implemented getting a token instead of new-ing up here. New is glue etc.

2023-10-10 11:58 UTC, johrs approved these changes

2023-11-17 14:51 UTC, ogrwill approved these changes

2023-12-07 12:20 UTC, merged